version: 2
jobs:
  build:    
    machine: 
      docker_layer_caching: false
    steps:
      - checkout
      - run: 
          name: Build Image
          command: docker build -t tojanke/build-env:debug .
          no_output_timeout: 2h          
      - run:
          name: Create Container, Retrieve Log Files          
          command: docker create --name b-env tojanke/build-env:debug && docker cp b-env:/log . && docker rm -f b-env
          when: always
      - store_artifacts:
          path: log
      - run:
          name: Log In to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish Docker Image to Docker Hub
          command: docker push tojanke/build-env:debug
workflows:
  version: 2
  commit:
    jobs:
      - build      
  update:
    triggers:
      - schedule:
          cron: "0 3 3 1,4,7,10 *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - build
